name: dynamicscontrol
channels:
  - conda-forge
  - defaults
dependencies:
  #- python=3.7.3
  - matplotlib
  - numpy
  - scipy
  - sympy
  - control
  - slycot
  - pandas
  - keras
  - tensorflow-base
  - scikit-learn
  - pytest
  - jupyter
  - ipython
  - ipywidgets
  - pytest-xdist
  - xlrd
  - openpyxl
  - patsy
  - pip # we need this for pip to work right
  - pip:
      - tbcontrol
