name: Run tests
run-name: Run tests
on: [push]
jobs:
  Run-Tests:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: dynamicscontrol
          environment-file: environment.yml
          python-version: 3.11
          auto-activate-base: false
      - run: pip install .
      - run: |
          pytest tests
          pytest --verbose test_all_notebooks.py
